language: node_js
node_js:
  - "10"
cache:
  yarn: true

install:
  - yarn install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  keep_history: true
  name: a245501835a
  email: 3547450@qq.com
  on:
    branch: master
